language: julia
sudo: false
os:
    - linux
addons:
  apt:
    packages:
    - libnlopt0
    - hdf5-tools
julia:
    - 1.7
matrix:
    allow_failures:
notifications:
    email: false
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'