name = "Inequality"
uuid = "131cd6a8-f02b-4a66-8ce5-0a80ec47b73f"
authors = ["Josep Espasa Reig <jespasareig@gmail.com> and contributors"]
version = "0.0.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.33"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
